# Generated by Django 4.2.7 on 2024-01-07 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_customuser_user_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[('A', 'Admin'), ('S', 'Staff'), (3, 'Teacher'), (4, 'Student'), (5, 'Parent')], default=1, max_length=1),
        ),
    ]
