# Generated by Django 4.2.7 on 2024-01-07 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_customuser_user_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[('Admin', 'Admin'), ('Staff', 'Staff'), ('Teacher', 'Teacher'), ('Student', 'Student'), ('Parent', 'Parent')], default=1, max_length=10),
        ),
    ]
